apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            {{- if .Values.development }}
            - name: http-dev
              containerPort: 8080
              protocol: TCP
            {{- end }}
          {{- if .Values.development }}
          workingDir: "/projects/{{ .Values.workingDir }}"
          volumeMounts:
            - name: "dev-volume"
              mountPath: "/projects"
            {{- range .Values.shadowMounts }}
            {{- if .enabled }}
            - name: "{{ .name }}-vol"
              mountPath: {{ .path | quote }}
            {{- end }}
            {{- end }}
          env:
            {{- range .Values.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
            {{- range .Values.envPaths }}
            - name: {{ .name | quote }}
              value: "/projects/{{ .value }}"
            {{- end }}
          {{- end }}
          {{- if not .Values.development }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
      {{- if .Values.development }}
      volumes:
        - name: "dev-volume"
          persistentVolumeClaim:
            claimName: {{ .Values.devVolumeClaim | default "bcs-dev-vol-pvc" }}
        {{- range .Values.shadowMounts }}
        {{- if .enabled }}
        - name: "{{ .name }}-vol"
          emptyDir:
            medium: {{ .medium | default "Memory" }}
            sizeLimit: {{ .sizeLimit | default "100Mi" }}
        {{- end }}
        {{- end }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.volumeMounts }}
      volumeMounts:
        {{- toYaml . | nindent 12 }}
      {{- end }}
